#ifndef CALIBRATIONCOMPONENT_GLOBAL_H
#define CALIBRATIONCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALIBRATIONCOMPONENT_LIBRARY)
#  define CALIBRATIONCOMPONENT_EXPORT Q_DECL_EXPORT
#else
#  define CALIBRATIONCOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // CALIBRATIONCOMPONENT_GLOBAL_H
